### ISSUE TITLE
Update Design Principle to be EPIC

### ISSUE THREAD

**Issue by garrettdigital** [vertigis/meridian-design#59]
Effective: Focus on creating software that enables users to efficiently and successfully complete their tasks. To achieve effectiveness, the user experience should prioritize usability and functionality, emphasizing intuitive user interfaces, clear navigation, and streamlined workflows. By designing for effectiveness, VertiGIS products can maximize user productivity and satisfaction, ultimately leading to a positive user experience. 

Polished: Create a visually appealing and refined experience. By adhering to a polished design aesthetic, VertiGIS products convey professionalism, credibility, and trustworthiness. Pay attention to the details, such as consistent and visually pleasing layouts, typography, color schemes, and imagery. Ensure that there are smooth transitions, responsive interactions, and error handling that provides a seamless user experience. 

Inclusive: Emphasize solutions that are accessible to all users, regardless of their abilities, disabilities, or technological limitations. Inclusive design involves considering a diverse range of users and their needs, including those with visual, auditory, motor, or cognitive impairments. By embracing inclusivity, VertiGIS products can reach a broader audience, promote equal opportunities, and enhance usability for everyone. 

Cohesive: Create a harmonious and consistent user experience throughout the suite of VertiGIS products. This involves maintaining a unified design language, visual style, and interaction patterns across different software solutions, features, and devices. By adhering to a cohesive design, VertiGIS products can foster a sense of familiarity and predictability, enabling users to navigate and interact with all VertiGIS products more confidently and efficiently.

**Comment by jfgodin** [comment]
EPIC!
